# Generated by Django 4.0.4 on 2022-06-10 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_organization_userorganization_organizationinvite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='most_recent_database',
        ),
    ]
