# Generated by Django 4.0.4 on 2022-06-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_most_recent_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_mode',
            field=models.IntegerField(choices=[('light', 1), ('dark', 2)], default=1),
        ),
    ]
