# Generated by Django 4.0.4 on 2022-06-15 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0010_delete_userqueryinfo'),
        ('users', '0005_profile_display_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='most_recent_database',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='queries.database'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_mode',
            field=models.IntegerField(choices=[(1, 'light'), (2, 'dark')], default=1),
        ),
    ]
