# Generated by Django 4.0.4 on 2022-08-21 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_profile_most_recent_database_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text="The email of the person you'd like to invite", max_length=128)),
                ('accepted', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text='Usually the name of your business or website', max_length=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_mode',
            field=models.IntegerField(choices=[(1, 'light'), (2, 'dark'), (3, 'synthwave')], default=3),
        ),
        migrations.DeleteModel(
            name='OrganizationInvite',
        ),
        migrations.AddField(
            model_name='invitation',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.organization'),
        ),
    ]
