# Generated by Django 4.0.4 on 2022-08-24 14:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='Can be any name you want such as "Transaction events"', max_length=256)),
                ('host', models.CharField(max_length=256)),
                ('port', models.IntegerField()),
                ('database', models.CharField(default='', help_text='The name of the database on your server', max_length=256)),
                ('user', models.CharField(help_text='Ideally with read-only permissions', max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('is_valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=64)),
                ('default', models.CharField(blank=True, max_length=256, null=True)),
                ('template', models.CharField(blank=True, help_text='for example: "AND timestamp > {v}"', max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('query', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True, help_text='Deactivate to remove query from search results. For example if the query is invalid.')),
                ('public', models.BooleanField(default=True, help_text='If public, your whole team can view it.  If not, only you.')),
                ('run_count', models.IntegerField(default=0)),
                ('last_run_date', models.DateTimeField(default=None, null=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('recent_error_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='QueryComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=256, null=True)),
                ('dataframe', models.TextField(null=True)),
                ('table', models.TextField(null=True)),
                ('single', models.CharField(max_length=64, null=True)),
                ('image_encoding', models.CharField(max_length=16, null=True)),
                ('chart', models.TextField(null=True)),
                ('preview', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('search', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(default='', max_length=64)),
                ('value', models.CharField(default='', max_length=256)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queries.result')),
            ],
        ),
    ]
