# Generated by Django 4.0.4 on 2022-05-26 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='content',
            new_name='query',
        ),
    ]
