# Generated by Django 4.0.4 on 2022-08-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='active',
        ),
        migrations.RemoveField(
            model_name='query',
            name='public',
        ),
        migrations.AddField(
            model_name='database',
            name='platform',
            field=models.CharField(choices=[('mysql', 'mysql'), ('postgres', 'postgres'), ('redshift', 'redshift')], default='mysql', max_length=64),
        ),
    ]
