# Generated by Django 4.0.4 on 2022-06-06 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('queries', '0004_remove_parameter_template_if_defined_and_more'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Topic',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('timestamp', models.DateTimeField(auto_now_add=True)),
        #         ('name', models.CharField(default='', max_length=32)),
        #     ],
        # ),
        migrations.AddField(
            model_name='value',
            name='value',
            field=models.CharField(default='', max_length=256),
        ),
        # migrations.CreateModel(
        #     name='QueryTopic',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queries.query')),
        #         ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queries.topic')),
        #     ],
        # ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=32)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queries.query')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
