# Generated by Django 4.0.4 on 2022-06-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0005_topic_value_value_querytopic_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
