# Generated by Django 4.0.4 on 2022-06-10 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('queries', '0006_query_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQueryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('most_recent_database', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='queries.database')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='query',
            name='active',
            field=models.BooleanField(default=True, help_text='Deactivate to remove query from search results. For example if the query is invalid.'),
        ),
        migrations.AddField(
            model_name='query',
            name='public',
            field=models.BooleanField(default=True, help_text='If public, your whole team can view it.  If not, only you.'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='template',
            field=models.CharField(blank=True, help_text='for example: "AND timestamp > {v}"', max_length=256, null=True),
        ),
    ]
