# Generated by Django 4.0.4 on 2022-06-10 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_most_recent_database'),
        ('queries', '0007_userqueryinfo_query_active_query_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='users.organization'),
        ),
    ]
