# Generated by Django 4.0.4 on 2022-06-10 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('queries', '0008_database_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userqueryinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='query_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
