# Generated by Django 4.0.4 on 2022-06-26 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0013_query_last_run_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraction',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='useraction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='result',
            name='instance',
        ),
        migrations.RemoveField(
            model_name='value',
            name='instance',
        ),
        migrations.AddField(
            model_name='result',
            name='query',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='queries.query'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='value',
            name='result',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='queries.result'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='result',
            name='chart',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='dataframe',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='preview',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Instance',
        ),
        migrations.DeleteModel(
            name='UserAction',
        ),
    ]
