# Generated by Django 4.0.4 on 2022-06-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0015_result_image_encoding_result_single_result_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='latest_chart',
            field=models.TextField(null=True),
        ),
    ]
