# Generated by Django 4.0.4 on 2022-07-31 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('queries', '0019_alter_result_dataframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='query',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='query',
            name='recent_error_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='QueryComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(null=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queries.query')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
