# Generated by Django 4.0.4 on 2022-08-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0020_database_is_valid_query_is_valid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='database',
            field=models.CharField(default='', help_text='The name of the database on your server', max_length=256),
        ),
        migrations.AlterField(
            model_name='database',
            name='title',
            field=models.CharField(default='', help_text='Can be any name you want such as "Transaction events"', max_length=256),
        ),
        migrations.AlterField(
            model_name='database',
            name='user',
            field=models.CharField(help_text='Ideally with read-only permissions', max_length=256),
        ),
    ]
